# Generated by Django 4.2.13 on 2026-01-13 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alert_category_taskstatus_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='imgProfile',
            field=models.URLField(blank=True, null=True),
        ),
    ]
